Add missing type annotation
fixes error TS7056: The inferred type of this node exceeds serializtion
limit.

Change-Id: I66927c80f2842b04301d3d381cf5fce9ab75a4b1